// <auto-generated />
using Hospital_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610212637_added-price-and-frequency-columns-withDataSeeding")]
    partial class addedpriceandfrequencycolumnswithDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_System.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. John Smith",
                            Price = 1000,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 2,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Ahmed Johnson",
                            Price = 2000,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 3,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Ali Davis",
                            Price = 5000,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 4,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Michael Lee",
                            Price = 5500,
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 5,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. William Clark",
                            Price = 6000,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            DoctorId = 6,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Salah Smith",
                            Price = 3000,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 7,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Ahmed Ali",
                            Price = 5000,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 8,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Ammar Mohammed",
                            Price = 1000,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 9,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Khaled Lee",
                            Price = 2200,
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 10,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Lee Clark",
                            Price = 3300,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            DoctorId = 11,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Eslam Lee",
                            Price = 1000,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 12,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Mofid Johnson",
                            Price = 2000,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 13,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Omar Ali",
                            Price = 5000,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 14,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Mahmoud Ismail",
                            Price = 5500,
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 15,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Ismail mohammed",
                            Price = 6000,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            DoctorId = 16,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Smith Simba",
                            Price = 2000,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 17,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Mosamba Johnson",
                            Price = 7000,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            DoctorId = 18,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Mousa Davis",
                            Price = 10000,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 19,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Yaqoub Smith",
                            Price = 6500,
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 20,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Lee Donald",
                            Price = 6700,
                            Specialization = "Neurology"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
