// <auto-generated />
using Hospital_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610232758_added-table-specialization-withDataSeeding")]
    partial class addedtablespecializationwithDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_System.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. John Smith",
                            Price = 1000,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Ahmed Johnson",
                            Price = 2000,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Ali Davis",
                            Price = 5000,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 4,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Michael Lee",
                            Price = 5500,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. William Clark",
                            Price = 6000,
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 6,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Salah Smith",
                            Price = 3000,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 7,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Ahmed Ali",
                            Price = 5000,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 8,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Ammar Mohammed",
                            Price = 1000,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 9,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Khaled Lee",
                            Price = 2200,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 10,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Lee Clark",
                            Price = 3300,
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 11,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Eslam Lee",
                            Price = 1000,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 12,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Mofid Johnson",
                            Price = 2000,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 13,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Omar Ali",
                            Price = 5000,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 14,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Mahmoud Ismail",
                            Price = 5500,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 15,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Ismail mohammed",
                            Price = 6000,
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 16,
                            Frequency = 0,
                            Img = "Images/doctor1.jpg",
                            Name = "Dr. Smith Simba",
                            Price = 2000,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 17,
                            Frequency = 0,
                            Img = "Images/doctor2.jpg",
                            Name = "Dr. Mosamba Johnson",
                            Price = 7000,
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 18,
                            Frequency = 0,
                            Img = "Images/doctor4.jpg",
                            Name = "Dr. Mousa Davis",
                            Price = 10000,
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 19,
                            Frequency = 0,
                            Img = "Images/doctor3.jpg",
                            Name = "Dr. Yaqoub Smith",
                            Price = 6500,
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 20,
                            Frequency = 0,
                            Img = "Images/doctor5.jpg",
                            Name = "Dr. Lee Donald",
                            Price = 6700,
                            SpecializationId = 5
                        });
                });

            modelBuilder.Entity("Hospital_System.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Name = "Dermatology"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Name = "Neurology"
                        });
                });

            modelBuilder.Entity("Hospital_System.Models.Doctor", b =>
                {
                    b.HasOne("Hospital_System.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Hospital_System.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
